config/routes.rb
Varyemez::Application.routes.draw do

  root :to => "home#index"
  
  match '/kontrol-panelim.html' => "home#main", :as => "login_success"
  match '/auth/:provider/callback' => 'authentications#create' 

  devise_for :users, :path => "uyeler", :controllers => { :registrations => 'registrations' }
  resources :authentications                                   
  resources :contacts, :path => "kisiler" do
    get 'alacaklar', :on => :collection
    get 'borclar', :on => :collection 
    post 'lock', :on => :member
    resources :credits
  end          
  resources :socialposts
  resources :mailsenders
  

end

app/models/contact.rb
#encoding:utf-8
class Contact < ActiveRecord::Base    
  require "unicode_utils/upcase"
   
  belongs_to :user 
  has_many :credits, :dependent => :destroy
               
  validates :user_id, :presence => true
  validates :first_name, :presence => {:message => "boş olmamalıdır."}
  validates :last_name, :presence => {:message => "boş olmamalıdır."}
  validates :email, :presence => {:message => "boş olmasın ki borçlarını hatırlatalım."}
  validates :email, :format => {:with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i, :message => "gerçerli değil !"}, :if => "email.present?"                   
                   

  scope :borclular, where(["debt > 0"])      
  scope :alacaklilar, where(["debt < 0"])                
  scope :vadesine_gore_borclular, lambda { |tarih=nil| includes(:credits).where(['debt > 0 and credits.date_to <= ?', "#{tarih}"]) }
                   
  def name
    "#{first_name.capitalize} #{UnicodeUtils.upcase(last_name, :tr)}"    
  end                                                        
  
  def lock_status
    lock ? "Evet" : "Hayır"
  end   
  
  def self.refresh_debt(contact)
    borc = contact.credits.where(:credit_type => 1).sum(:amount)
    alacak = contact.credits.where(:credit_type => 2).sum(:amount)
    contact.update_attributes(:debt => borc-alacak)
  end
                   
end

app/controllers/contacts_controller.rb
#encoding:utf-8
class ContactsController < ApplicationController 
  
  def index             
    @contacts = current_user.contacts    
  end            
  
  def new
    @contact = Contact.new
  end
  
  def create   
    @contact = Contact.new(params[:contact]) 
    @contact.user = current_user
    if @contact.save
      redirect_to contacts_path, :notice => "Yeni kişi başarılı bir şekilde oluşturuldu."
    else            
      flash[:notice] = "Yeni kişi kaydında hata ile karşılaşıldı."
      render :new
    end
  end   
  
  def edit
    @contact = Contact.find(params[:id])
  end    
  
  def update
    @contact = Contact.find(params[:id])
    @contact.user_id = current_user.id
    if @contact.update_attributes(params[:contact])
      redirect_to contacts_path, :notice => "Kayıt başarılı bir şekilde güncellendi."
    else
      flash[:notice] = "Güncelleme formunda hata ile karşılaşıldı."
      render :edit
    end
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
  end  
  
  def alacaklar
    @contacts = current_user.contacts.borclular.select("id, first_name, last_name, debt, phone, email")
    respond_to do |format|
      format.html
      format.xls { send_data @contacts.to_xls }
    end
  end                                                                             

  def borclar
    @contacts = current_user.contacts.alacaklilar.select("id, first_name, last_name, debt, phone, email")
    respond_to do |format|
      format.html
      format.xls { send_data @contacts.to_xls }
    end
  end   
  
  def lock
    @contact = Contact.find(params[:id])
    @contact.update_attributes(:lock => !@contact.lock)
    redirect_to contacts_path
  end
     
end

app/helpers/contacts_helper.rb
#encoding:utf-8
module ContactsHelper
  
  def lock_action(contact)
    if contact.lock_status == "Hayır"
      link_to "Kilitle", lock_contact_path(contact.id), :method => :post
    else
      link_to "Kilidi Aç", lock_contact_path(contact.id), :method => :post
    end
  end
   
end

app/views/contacts/_contact.html.erb
<tr id="contact_<%= contact.id %>">
	<td><%= image_tag avatar(contact.email, 36) %></td>
	<td><%= image_tag("lock.png") if contact.lock_status == "Evet" %><%= link_to contact.name, contact_path(contact) %></td>
	<td><%= contact.email %></td>
	<td><%= contact.phone %></td>
	<td><%= contact.sex %></td>
	<td><%= contact.limit %></td> 
	<td>
		<%= link_to "Sil", contact_path(contact), :method => :delete, :remote => true %> 
		<%= link_to "Güncelle", edit_contact_path(contact) %>
		<%= lock_action(contact) %>		
	</td>
 </tr>

app/views/contacts/alacaklar.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>  
	<h4 style="color:red;">Borçlu olanların listesi<h4>         

	<div class="with-table">
		<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<thead>
			<tr>        
				<th></th>
				<th scope="col">Adı Soyadı</th>
				<th scope="col">Borç</th>
				<th scope="col">E-Mail</th>
				<th scope="col">Telefon</th>   				 
				<th></th>   	 
			</tr> 
			</thead>      
			<tbody>
				<% @contacts.each do |contact| %>
					<tr id="contact_<%= contact.id %>">
						<td><%= image_tag avatar(contact.email, 36) %></td>
						<td><%= link_to contact.name, contact_path(contact) %></td>
						<td><%= para_birimi contact.debt %></td>
						<td><%= contact.email %></td>
						<td><%= contact.phone %></td>						
						<td></td>
					 </tr>
				<% end %>	
			</tbody>
		</table>               
	</div>
	<div class="grid_4">
		<%= link_to "Excel'e Aktar", alacaklar_contacts_path(format: "xls"), :class => "button" %>
	</div>
</div>

app/views/contacts/borclar.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>  
	<h4 style="color:red;">Alacaklı olanların listesi<h4>         
	<div class="with-table">
		<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<thead>
			<tr>        
				<th></th>
				<th scope="col">Adı Soyadı</th>
				<th scope="col">Borç</th>
				<th scope="col">E-Mail</th>
				<th scope="col">Telefon</th>   				 
				<th></th>   	 
			</tr> 
			</thead>      
			<tbody>
				<% @contacts.each do |contact| %>
					<tr id="contact_<%= contact.id %>">
						<td><%= image_tag avatar(contact.email, 36) %></td>
						<td><%= link_to contact.name, contact_path(contact) %></td>
						<td><%= para_birimi contact.debt %></td>
						<td><%= contact.email %></td>
						<td><%= contact.phone %></td>						
						<td></td>
					 </tr>
				<% end %>	
			</tbody>
		</table>               
	</div>
	<div class="grid_4">
		<%= link_to "Excel'e Aktar", borclar_contacts_path(:format => "xls"), :class => "button" if @contacts.any? %>
	</div>
</div>

app/views/contacts/create.js.erb
<% if @contact.errors.any? %>
	alert(<%= @hatalar.join('\n') %>);
<% else %>
	$("#hor-minimalist-b > tbody:last").append("<%= escape_javascript(render @contact) %>");
<% end %>

app/views/contacts/destroy.js.erb
$("#contact_<%= @contact.id %>").fadeOut();

app/views/contacts/edit.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>
	<% if @contact.errors.any? %>
	<div class="grid_120 error-box">
		<h4>Murat güzel<%= notice %></h4>
		<p>
			<ul>
				<% @contact.errors.full_messages.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul
		 <p>
	</div>
	<% end %>  
	<div class="with-table">
		<div id="stylized" class="myform" style="width:400px;height:430px;overflow:auto;">     
			<%= form_for @contact do |f| %>
				<h1>Güncelle</h1>
				<p>Formu doldurarak <%= @contact.name %> adlı kişinin bilgilerini güncelleyebilirsiniz.</p>

				<label>Adı<span class="small">Kişinin adını giriniz</span></label>        			 
				<%= f.text_field :first_name %>

				<label>Soyadı<span class="small">Kişinin soyadını giriniz</span></label>        			 
				<%= f.text_field :last_name %>

				<label>E-Mail</label>        			 
				<%= f.text_field :email %>

				<label>Telefon</label>        			 
				<%= f.text_field :phone %>

				<label>Risk Limiti<span class="small">Bu kişi için risk limiti (TL)</span></label>        			 
				<%= f.text_field :limit %>

				<label>Cinsiyet</label>        			 
				<%= f.select :sex, ["Bayan", "Bay"] %>  

				<br /><br />

				<%= f.submit "Güncelle", :disable_with => 'Güncelleniyor...', :class => "button" %>
				<div class="spacer"></div>

			<% end %>	
		</div>       
	</div>
</div>         

</div>

app/views/contacts/index.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>    
    <h4><%= notice %></h4>
	<%= link_to "Yeni Kişi Kaydı", new_contact_path, :class => "button" %>            
	<div class="with-table">
		<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<thead>
			<tr>        
				<th></th>
				<th scope="col">Adı Soyadı</th>
				<th scope="col">E-Posta</th>
				<th scope="col">Tel</th>
				<th scope="col">Cinsiyet</th>
				<th scope="col">Risk Limit</th>	 
				<th></th>   	 
			</tr> 
			</thead>      
			<tbody>
				<%= render @contacts %>	
			</tbody>
		</table>               
	</div>
</div>         
<script> 
$("#various1").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});
</script>
<div style="display: none;">
	<div id="stylized" class="myform" style="width:400px;height:400px;overflow:auto;">     
		<%= form_for Contact.new, :remote => true do |f| %>
			<h1>Yeni Kişi Kaydı</h1>
			<p>Formu doldurarak yeni kişi kaydını oluşturabilirsiniz.</p>

			<label>Adı<span class="small">Kişinin adını giriniz</span></label>        			 
			<%= f.text_field :first_name %>

			<label>Soyadı<span class="small">Kişinin soyadını giriniz</span></label>        			 
			<%= f.text_field :last_name %>

			<label>E-Mail</label>        			 
			<%= f.text_field :email %>

			<label>Telefon</label>        			 
			<%= f.text_field :phone %>

			<label>Risk Limiti<span class="small">Bu kişi için risk limiti (TL)</span></label>        			 
			<%= f.text_field :limit %>

			<label>Cinsiyet</label>        			 
			<%= f.select :sex, ["Bayan", "Bay"] %>  

			<br /><br />

			<%= f.submit "Kaydet", :disable_with => 'Kaydediliyor...', :class => "button" %>
			<div class="spacer"></div>

		<% end %>	
	</div>
</div>

app/views/contacts/lock.js.erb
alert("işlem tamam");

app/views/contacts/new.html.erb
<div id="stylized" class="myform">     
	<%= form_for @contact do |f| %>
		<h1>Yeni Kişi Kaydı</h1>
		<p>Formu doldurarak yeni kişi kaydını oluşturabilirsiniz.</p>
		 
		<label>Adı<span class="small">Kişinin adını giriniz</span></label>        			 
		<%= f.text_field :first_name %>

		<label>Soyadı<span class="small">Kişinin soyadını giriniz</span></label>        			 
		<%= f.text_field :last_name %>

		<label>E-Mail</label>        			 
		<%= f.text_field :email %>
		
		<label>Telefon</label>        			 
		<%= f.text_field :phone %>
		
		<label>Risk Limiti<span class="small">Bu kişi için risk limiti (TL)</span></label>        			 
		<%= f.text_field :limit %>
		
		<label>Cinsiyet</label>        			 
		<%= f.select :sex, ["Bayan", "Bay"] %>  
		
		<br /><br />

		<%= f.submit "Kaydet", :disable_with => 'Kaydediliyor...', :class => "button" %>
		<div class="spacer"></div>
		
	<% end %>	
</div>

app/views/contacts/show.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>
	<div class="grid_3">
		<%= image_tag avatar(@contact.email, 200), :class => "border" %>
	</div>                                                           
	<div class="grid_9 last">
		<h2><%= @contact.name %></h2>
		<table class="ident_table">
			<tr>
				<td>E-Mail : </td>
				<td><%= @contact.email.downcase %></td>
			</tr>
			<tr>
				<td>Telefon : </td>
				<td><%= @contact.phone %></td>
			</tr> 			
			<tr>
				<td>Cinsiyet : </td>
				<td><%= @contact.sex %></td>
			</tr>                   
			<tr>
				<td>Güncel Bakiye : </td>
				<td id="guncel_bakiye"><%= para_birimi(@contact.debt) %></td>
			</tr>
			<tr>
				<td>Risk Limiti : </td>
				<td><%= para_birimi(@contact.limit) %></td>
			</tr>                     
			<tr>
				<td>Kilit : </td>
				<td><%= @contact.lock_status %></td>
			</tr>			
		</table>
	</div>
	<div class="grid_12">    
		<hr />
		<h3>Hesap Dökümü</h3>	
		<% if @contact.lock_status == "Evet" %>
			<div class="grid_12 uyari">
				<h6><%= @contact.name %> hesabı kilitli olduğu için yeni borç/alacak kaydı yapamaz ve mevcut kayıtları güncelleyemezsiniz.</h6>
			</div>  	                       
		<% end %>
		<div class="grid_8">
			<% if @contact.debt > 0 %>     
				<%= link_to "Bilgilendirme Mail Gönder", mailsenders_path(:email => @contact.email, :name => @contact.name, :debt => @contact.debt), :method => :post, :remote => true, :class => "button" %>
		   		<%= link_to "Sosyal Medyada İfşa Et", socialposts_path(:tweet => "#{@contact.name} bana borcunu ödemiyor. Borcu #{para_birimi @contact.debt} oldu."), :method => :post, :remote => true, :class => "button" %> 
	   		<% end %>
			<%= link_to "PDF Al", contact_credits_path(@contact, :format => "pdf"), :class => "button" %> 
			<% if @contact.lock_status == "Hayır" %>
				<%= link_to "Yeni Borç / Alacak Kaydı", new_contact_credit_path(@contact), :class => "button" %>
			<% end %>
		</div>                                                                                              
		<div class="grid_12"><br /></div>
		<div class="with-table">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<thead>
				<tr>        
					<th scope="col">İşlem Tarihi</th>
					<th scope="col">Vade Tarihi</th>
					<th scope="col">Borç</th>
					<th scope="col">Alacak</th>
					<th scope="col">Açıklama</th>	 
					<th></th>   	 
				</tr> 
				</thead>      
				<tbody>
					<%= render @contact.credits %>	
				</tbody>
			</table>               
		</div>		
	</div> 
</div>     
<script> 
$("#various1").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});
</script>
<div style="display: none;">
	<div id="stylized" class="myform" style="width:270;height:370px;overflow:auto;">     
		<%= form_for [@contact, Credit.new], :remote => true do |f| %>
			<h1>Borç / Alacak İşle</h1>
			<p>Formu doldurarak yeni kişi kaydını oluşturabilirsiniz.</p>

			<label>Tarih<span class="small">İşlem yapılan tarih</span></label>        			 
			<%= f.text_field :date_from %>

			<label>Vade Tarihi<span class="small">Vade tarihi</span></label>        			 
			<%= f.text_field :date_to %>

			<label>Tutar</label>        			 
			<%= f.text_field :amount %>
			
			<label>Açıklama<span class="small">En fazla 80 karakter</span></label>        			 
			<%= f.text_field :description %>

			<label>İşlem Tipi<span class="small">Borç / Alacak</span></label>        			 
			<%= f.select :credit_type, [["Borç", 1],["Alacak", 2]]  %>



			<br /><br />

			<%= f.submit "Kaydet", :disable_with => 'Kaydediliyor...', :class => "button" %>
			<div class="spacer"></div>

		<% end %>	
	</div>
</div>