config/routes.rb
Varyemez::Application.routes.draw do

  root :to => "home#index"
  
  match '/kontrol-panelim.html' => "home#main", :as => "login_success"
  match '/auth/:provider/callback' => 'authentications#create' 

  devise_for :users, :path => "uyeler", :controllers => { :registrations => 'registrations' }
  resources :authentications                                   
  resources :contacts, :path => "kisiler" do
    get 'alacaklar', :on => :collection
    get 'borclar', :on => :collection 
    post 'lock', :on => :member
    resources :credits
  end          
  resources :socialposts
  resources :mailsenders
  

end

app/models/credit.rb
#encoding:utf-8
class Credit < ActiveRecord::Base 
  belongs_to :contact
  
  validates :date_from, :presence => true
  validates :date_to, :presence => true                      
  validates :amount, :numericality => true
  validate :date_from_would_not_be_greater_then_date_to, :if => "date_from.present? && date_to.present?"
  
  after_create :credit_created             
  
  def date_from_would_not_be_greater_then_date_to
    if self.date_to < self.date_from
      errors.add :date_to, "daha eski bir tarih olamaz. Sence de mantıksız değil mi ?"
    end
  end                                                                                                  
 
  def borc_verilebilirmi
    #risk limiti kontrolü yapıyor ...     
    if self.contact.limit.nil? || self.contact.limit == 0
      # risk limiti tanımlı değil. O halde borç verilen tutar tahsil edilmeden yeni borç verilmemesi gerektiği uyarılacak ... 
      if self.credit_type == 1 && self.contact.debt > 1
        return false
      else
        return true
      end
    else
      if self.credit_type == 1 && (self.contact.limit < (self.amount + self.contact.debt))
        return false
      else
        return true
      end        
    end    
  end
  
  def credit_created
    if self.credit_type == 1 # borç verilmiş      
      self.contact.update_attributes(:debt => self.contact.debt + self.amount)           
    else # borcunu ödemiş
      self.contact.update_attributes(:debt => self.contact.debt - self.amount)      
    end
  end
  
  def borc
    self.amount if credit_type == 1
  end
  
  def alacak                       
    self.amount if credit_type == 2
  end                         
  
  
end

app/controllers/credits_controller.rb
#encoding:utf-8
class CreditsController < ApplicationController
  before_filter :get_contact
  
  def get_contact
    @contact = Contact.find(params[:contact_id])
  end   
  
  def index
    @credits = @contact.credits
    respond_to do |format|
      format.pdf do
        pdf = HesapDokumPdf.new(@contact, view_context)
        send_data pdf.render, :filename => "#{@contact.name} Hesap Dökümü", :type => "application/pdf", :dispoisition => "inline"
      end
    end
  end 
  
  def new
    @credit = @contact.credits.build
  end
  
  def create
    @credit = @contact.credits.build(params[:credit]) 
    
    # limit değerleri kontrol edilecek ve uyarı varsa verilecek.
    if !params[:accept]
      unless @credit.borc_verilebilirmi
        flash[:alert] = "Borç vermenizi şiddetle tavsiye etmiyorum."
        render :new; return
      end              
    end
    
    if @credit.save 
      redirect_to contact_path(@contact), :notice => "Kayıt başarılı bir şekilde gerçekleştirildi."
    else        
      flash[:notice] = "Kayıt girişinde hata ile karşılaşıldı"
      render :new
    end   
  end           
  
  def edit
    @credit = @contact.credits.find(params[:id])    
  end     
  
  def update
    @credit = @contact.credits.find(params[:id]) 
    @credit.update_attributes(params[:credit])
    if @credit.save 
      Contact.refresh_debt(@contact) 
      redirect_to contact_path(@credit.contact), :notice => "Borç/Alacak kaydı güncellemesi yapıldı."
    else          
      flash[:alert] = "Güncelleme formunda hata ile karşılaşıldı."
      render :edit
    end                                                                                              
    
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
  
end

app/views/credits/_credit.html.erb
<tr id="credit_<%= credit.id %>">           
	<td><%= tarih_format credit.date_from %></td>
	<td><%= tarih_format credit.date_to %></td>
	<td style="color:red;"><%= para_birimi credit.borc %></td>
	<td style="color:red;"><%= para_birimi credit.alacak %></td>
	<td><%= credit.description.truncate(80) %></td>	 
	<td><%= link_to_if credit.contact.lock_status == "Hayır", "Güncelle", edit_contact_credit_path(credit.contact, credit)  %></td>                                     
</tr>

app/views/credits/create.js.erb
<% unless @credit.errors.any? %>
$("#hor-minimalist-b > tbody:last").append("<%= escape_javascript(render @credit) %>");
$("#guncel_bakiye").empty();
$("#guncel_bakiye").append("<%= escape_javascript para_birimi(@credit.contact.debt) %>");
<% end %>

app/views/credits/edit.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>
	<div class="grid_3">
		<%= image_tag avatar(@credit.contact.email, 200), :class => "border" %>
	</div>                                                           
	<div class="grid_9 last">
		<h2><%= @credit.contact.name %></h2>
		<table class="ident_table">
			<tr>
				<td>E-Mail : </td>
				<td><%= @credit.contact.email.downcase %></td>
			</tr>
			<tr>
				<td>Telefon : </td>
				<td><%= @credit.contact.phone %></td>
			</tr> 			
			<tr>
				<td>Cinsiyet : </td>
				<td><%= @credit.contact.sex %></td>
			</tr>                   
			<tr>
				<td>Güncel Bakiye : </td>
				<td id="guncel_bakiye"><%= para_birimi(@credit.contact.debt) %></td>
			</tr>
			<tr>
				<td>Risk Limiti : </td>
				<td><%= para_birimi(@credit.contact.limit) %></td>
			</tr>                     
			<tr>
				<td>Kilit : </td>
				<td><%= @credit.contact.lock_status %></td>
			</tr>			
		</table>
	</div>
	<div class="grid_12">    
		<hr />
		<h3>Hesap Dökümü</h3>	
		<p><%= flash[:notice] %></p> 
	 	<div id="stylized" class="myform" style="width:270;height:370px;overflow:auto;">     
			<%= form_for [@credit.contact, @credit] do |f| %>
				<h1>Borç / Alacak İşle</h1>
				<p>Formu doldurarak yeni kişi kaydını oluşturabilirsiniz.</p>

				<label>Tarih<span class="small">İşlem yapılan tarih</span></label>        			 
				<%= f.text_field :date_from %>

				<label>Vade Tarihi<span class="small">Vade tarihi</span></label>        			 
				<%= f.text_field :date_to %>

				<label>Tutar</label>        			 
				<%= f.text_field :amount %>

				<label>Açıklama<span class="small">En fazla 80 karakter</span></label>        			 
				<%= f.text_field :description %>

				<label>İşlem Tipi<span class="small">Borç / Alacak</span></label>        			 
				<%= f.select :credit_type, [["Borç", 1],["Alacak", 2]]  %>


				<br /><br />

				<%= f.submit "Kaydet", :disable_with => 'Kaydediliyor...', :class => "button" %>
				<div class="spacer"></div>

			<% end %>	
		</div>
			
	</div> 
</div>     

app/views/credits/new.html.erb
<div class="container_12">      
	<%= render "shared/menu" %>
	<div class="grid_3">
		<%= image_tag avatar(@credit.contact.email, 200), :class => "border" %>
	</div>                                                           
	<div class="grid_9 last">
		<h2><%= @credit.contact.name %></h2>
		<table class="ident_table">
			<tr>
				<td>E-Mail : </td>
				<td><%= @credit.contact.email.downcase %></td>
			</tr>
			<tr>
				<td>Telefon : </td>
				<td><%= @credit.contact.phone %></td>
			</tr> 			
			<tr>
				<td>Cinsiyet : </td>
				<td><%= @credit.contact.sex %></td>
			</tr>                   
			<tr>
				<td>Güncel Bakiye : </td>
				<td id="guncel_bakiye"><%= para_birimi(@credit.contact.debt) %></td>
			</tr>
			<tr>
				<td>Risk Limiti : </td>
				<td><%= para_birimi(@credit.contact.limit) %></td>
			</tr>                     
			<tr>
				<td>Kilit : </td>
				<td><%= @credit.contact.lock_status %></td>
			</tr>			
		</table>
	</div>
	<div class="grid_12">    
		<hr />
		<h3>Hesap Dökümü</h3>	 
		<%= form_for [@credit.contact, @credit] do |f| %>
		<p style="color:red;"><%= notice %></p> 
		<div class="error">
			<% if @credit.errors.any? %>
			<ul>   
				<% @credit.errors.full_messages.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul>                     
			<% end %>  			                            
		</div> 
		<% unless alert.blank? %>
			<label>Emin misiniz ?</label>        			 
			<%= check_box_tag "accept", :value => "Uyarıya rağmen borç vermeyi kabul ediyorum." %> 
		<% end %> 
	 	<div id="stylized" class="myform" style="width:270;height:370px;overflow:auto;">     
			
				<h1>Borç / Alacak İşle</h1>
				<p>Formu doldurarak yeni kişi kaydını oluşturabilirsiniz.</p>

				<label>Tarih<span class="small">İşlem yapılan tarih</span></label>        			 
				<%= f.text_field :date_from %>

				<label>Vade Tarihi<span class="small">Vade tarihi</span></label>        			 
				<%= f.text_field :date_to %>

				<label>Tutar</label>        			 
				<%= f.text_field :amount, :id => "tutar_field" %>

				<label>Açıklama<span class="small">En fazla 80 karakter</span></label>        			 
				<%= f.text_field :description %>
				
				

				<label>İşlem Tipi<span class="small">Borç / Alacak</span></label>        			 
				<%= f.select :credit_type, [["Borç", 1],["Alacak", 2]]  %>  



				<br /><br />

				<%= f.submit "Kaydet", :disable_with => 'Kaydediliyor...', :class => "button" %>
				<div class="spacer"></div>
	
		</div>
					<% end %>
			
	</div> 
</div>